var heading = document.createElement("h2")
var node = document.createTextNode("Merhaba!")
heading.appendChild(node)
var div1 = document.getElementById("div1")
var p2 = document.getElementById("p2")
div1.insertBefore(heading,p2)
alert("Değiştiriliyor")
var p1 = document.getElementById("p1")
div1.replaceChild(heading,p1)